name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Launch MongoDB
        run:  sudo docker run --name mongo -d -p 27017:27017 mongo
      - name: Test
        run: npm test

